# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('LS', 'Life Stage'), ('SN', 'Special Nutrition'), ('DS', 'Dog Size'), ('QL', 'Quality'), ('OT', 'Other')], default='OT', max_length=2)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='DogFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('photo', models.ImageField(blank=True, default='misc\\no-image.jpg', null=True, upload_to='uploads/')),
                ('food_type', models.CharField(choices=[('DR', 'Dry Food'), ('RW', 'Raw Food'), ('CN', 'Canned Food'), ('FR', 'Fresh Food'), ('OT', 'Other Food')], default='DR', max_length=2)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogfoods', to='doggyfood.Brand')),
                ('category', models.ManyToManyField(related_name='dogfoods', to='doggyfood.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.FloatField(blank=True, null=True)),
                ('dog_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_composition', to='doggyfood.DogFood')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_composition', to='doggyfood.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.FloatField(blank=True, null=True)),
                ('dog_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_composition', to='doggyfood.DogFood')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('dogfood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doggyfood.DogFood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nutritionalcomposition',
            name='nutritional_fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_composition', to='doggyfood.NutritionalFact'),
        ),
        migrations.AddField(
            model_name='dogfood',
            name='ingredients',
            field=models.ManyToManyField(related_name='dogfoods', to='doggyfood.Ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='nutritionalcomposition',
            unique_together=set([('nutritional_fact', 'dog_food')]),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientcomposition',
            unique_together=set([('ingredient', 'dog_food')]),
        ),
    ]
