# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggyfood', '0002_remove_dogfood_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogfood',
            name='compare',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dogfood',
            name='food_type',
            field=models.CharField(choices=[('DR', 'Dry Food'), ('RW', 'Raw Food'), ('CN', 'Canned Food'), ('FR', 'Fresh Food'), ('OT', 'Other Food')], default='DR', max_length=2),
        ),
    ]
