# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doggyfood', '0002_dogfood_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('dog_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='doggyfood.DogFood')),
            ],
        ),
    ]
