# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggyfood', '0003_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogfood',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
