# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggyfood', '0004_auto_20160630_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='dog_food',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dog_food',
            field=models.ManyToManyField(related_name='ingredient', to='doggyfood.DogFood'),
        ),
    ]
