# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggyfood', '0005_auto_20160630_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='dog_food',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dog_foods',
            field=models.ManyToManyField(blank=True, related_name='ingredient', to='doggyfood.DogFood'),
        ),
    ]
